### ISSUE TITLE
Update Dataset 

### ISSUE THREAD

**Issue by sanjus-robotic-studio** [sanjus-robotic-studio/face-mask-detector#6]
Hi, 
    In this issue you need to add dataset to the dataset folder .ie people with mask and people without mask. First to comment will be assigned. You have 7 days. You need to add atleast 300 photos in each category.

- [ ] Add additional dataset

**Comment by divyansh1110** [comment]
hi,
sanjus robotic studio I will be happy to solve your issue

**Comment by sanjus-robotic-studio** [comment]
> hi,
> sanjus robotic studio I will be happy to solve your issue 

We shall give chances for others too

**Comment by Yugal41735** [comment]
Hello,  i g this issue is closed because there are already 1000 images in both the cases

**Comment by sanjus-robotic-studio** [comment]
> Hello,  i g this issue is closed because there are already 1000 images in both the cases
> 

I am telling you to add additional data to it

**Comment by Yugal41735** [comment]
ok then i will take up the issue then

**Comment by sanjus-robotic-studio** [comment]
All the best. Try to complete it by the time
Happy Coding :)

**Comment by Yugal41735** [comment]
Thanku, one thing more i want to ask is should a photo should contain group of people or only a single person
