### ISSUE TITLE
Update training script

### ISSUE THREAD

**Issue by sanjus-robotic-studio** [sanjus-robotic-studio/face-mask-detector#7]
Hi,
    In this you need to upgrade the training script. You will have seven days time. Contact me for details. First to comment will be assigned.

- [ ] Upgrade the training script

**Comment by divyansh1110** [comment]
hi,
sanjus robotic studio I will be happy to solve your issue

**Comment by sanjus-robotic-studio** [comment]
All the best. Complete it within one week

**Comment by divyansh1110** [comment]
Can I receive a mail regarding the task to be done in the training script?

**Comment by divyansh1110** [comment]
Can I receive a mail regarding the task to be done in the training script?

**Comment by sanjus-robotic-studio** [comment]
Send me your mail address

**Comment by divyansh1110** [comment]
***@***.***

**Comment by divyansh1110** [comment]
divyanshchawda1@gmail.com
